#!/bin/bash

query_ripe () {
  local ripe_block=$1
  local as_number=$2
  ripe_url="https://stat.ripe.net/data/announced-prefixes/data.json?resource=$as_number"
  folder="/scripts/archive-ripe-bgp-$ripe_block"
  list_raw="$folder/$(date -I)_bgp-$ripe_block-list"
  list_rsc="$folder/$(date -I)_bgp-$ripe_block.rsc"
  was_empty=no
  if [[ $(ls "$folder"|wc -l) == 0 ]]; then
    dummy="$folder/empty.rsc"
    touch $dummy
    was_empty=yes
  fi
  list_rsc_prev_month="$(ls -t1 $folder/*rsc | head -1)"

  if [ ! -d $folder ]; then
    mkdir -p $folder
  fi

  curl -s $ripe_url | jq ".data.prefixes[].prefix" | sed -n '/:/!p' | sed 's/[^0-9./-]*//g' > $list_raw

  > $list_rsc

  while read -r line || [[ -n "$line" ]]
  do
    echo ":do { /ip firewall address-list add list=bgp-$ripe_block comment=$as_number address=$line } on-error={}" >> $list_rsc
  done < "$list_raw"

  router_ssh="ssh -T robot@fw.lan"
  md5_current=$(md5sum "$list_rsc" | cut -d " " -f1)
  md5_previous=$(md5sum "$list_rsc_prev_month" | cut -d " " -f1)

  if [ "$md5_current" != "$md5_previous" ]; then
    > addlines
    > deladdress
    > dellines
    diff $list_rsc_prev_month $list_rsc | grep '> ' | sed 's/^> //' >> addlines
    diff $list_rsc_prev_month $list_rsc | grep '< '| sed 's/^.*address\=//' | sed 's/ .*//' >> deladdress
    if [[ -s deladdress ]]; then
      while read -r adresa
      do
        $router_ssh ":log info \"Changes detected in $as_number compared to existing version. Removing entries from bgp-$ripe_block address list.\""
        echo ":do { /ip firewall address-list remove [find where list=bgp-$ripe_block comment=$as_number address=$adresa] } on-error={}" >> dellines
      done < deladdress
      $router_ssh < dellines
    fi
    if [[ -s addlines ]]; then
      $router_ssh ":log info \"Changes detected in $as_number compared to existing version. Adding entries to bgp-$ripe_block address list.\""
      $router_ssh < addlines
    fi
    rm addlines deladdress dellines
    if [ $was_empty == "yes" ]; then
    echo
      rm $dummy
    fi
  else
    $router_ssh ":log info \"The bgp-$ripe_block address list has no changes compared to the existing version.\""
  fi
}