#!/bin/bash

ripe_url="https://stat.ripe.net/data/announced-prefixes/data.json?resource=AS205714"
folder="/home/che/scripts/archive-ripe-bgp-telemach-hr"
list_raw="$folder/$(date -I)_bgp-telemach-hr_list"
list_rsc="$folder/$(date -I)_bgp-telemach-hr.rsc"
was_empty=no
if [[ $(ls "$folder"|wc -l) == 0 ]]; then
  dummy="$folder/empty.rsc"
  touch $dummy
  was_empty=yes
fi
list_rsc_prev_month="$(ls -t1 $folder/*rsc | head -1)"

if [ ! -d $folder ]; then
  mkdir -p $folder
fi

curl -s $ripe_url | jq ".data.prefixes[].prefix" | sed -n '/:/!p' | sed 's/[^0-9./-]*//g' > $list_raw

> $list_rsc

while read -r line || [[ -n "$line" ]]
do
  echo ":do { /ip firewall address-list add list=bgp-telemach-hr comment=AS205714 address=$line } on-error={}" >> $list_rsc
done < "$list_raw"

router_ssh="ssh -T robot@fw.lan"
md5_current=$(md5sum "$list_rsc" | cut -d " " -f1)
md5_previous=$(md5sum "$list_rsc_prev_month" | cut -d " " -f1)

if [ "$md5_current" != "$md5_previous" ]; then
  > addlines
  > deladdress
  > dellines
  diff $list_rsc_prev_month $list_rsc | grep '> ' | sed 's/^> //' >> addlines
  diff $list_rsc_prev_month $list_rsc | grep '< '| sed 's/^.*address\=//' | sed 's/ .*//' >> deladdress
  if [[ -s deladdress ]]; then
    while read -r adresa
    do
      $router_ssh ":log info \"Changes detected in AS205714 compared to existing version. Removing entries from bgp-telemach-hr address list.\""
      echo ":do { /ip firewall address-list remove [find where list=bgp-telemach-hr comment=AS205714 address=$adresa] } on-error={}" >> dellines
    done < deladdress
    $router_ssh < dellines
  fi
  if [[ -s addlines ]]; then
    $router_ssh ":log info \"Changes detected in AS205714 compared to existing version. Adding entries to bgp-telemach-hr address list.\""
    $router_ssh < addlines
  fi
  rm addlines deladdress dellines
  if [ $was_empty == "yes" ]; then
  echo
    rm $dummy
  fi
else
  $router_ssh ":log info \"The bgp-telemach-hr address list has no changes compared to the existing version.\""
fi