#!/bin/bash
ripe_url="https://stat.ripe.net/data/announced-prefixes/data.json?resource=AS31042"
folder="/home/che/scripts/archive-ripe-bgp-sbb"
ipv4_bgp_sbb="$folder/$(date -I)_bgp-sbb_list"
file="$folder/$(date -I)_bgp-sbb.rsc"
old_file="$(ls -1 $folder | grep $(date -d "$(date -I) last month" +%Y-%m)|grep .rsc)"
previous_file="$folder/$old_file"

if [ ! -d $folder ]; then
	mkdir -p $folder
fi

curl -s https://stat.ripe.net/data/announced-prefixes/data.json?resource=AS31042 | jq ".data.prefixes[].prefix" | sed -n '/:/!p' | sed 's/[^0-9./-]*//g' > $ipv4_bgp_sbb

> $file

while read -r line || [[ -n "$line" ]]
do
	echo ":do { /ip firewall address-list add list=access-wan-bgp-sbb address=$line } on-error={}" >> $file
done < "$ipv4_bgp_sbb"

router_ssh="ssh -T robot@192.168.11.254"
md5_current=$(md5sum "$file" | cut -d " " -f1)
md5_previous=$(md5sum "$previous_file" | cut -d " " -f1)

if [ $md5_current != $md5_previous ]; then
	> addlines
	> deladdress
	> dellines
	diff $previous_file $file | grep '> ' | sed 's/^> //' >> addlines
	diff $previous_file $file | grep '< '| sed 's/^.*address\=//' | sed 's/ .*//' >> deladdress
        if [[ -s addlines ]]; then
		$router_ssh < addlines
	fi
	if  [[ -s deladdress ]]; then
		while read -r adresa
		do
			echo ":do { /ip firewall address-list remove [find where list=access-wan-bgp-sbb address=$adresa] } on-error={}" >> dellines
		done < deladdress
		$router_ssh < dellines
	fi
	rm addlines deladdress dellines
else
	echo "The access-wan-bgp-sbb list has no changes compared to previous month."
fi
