#!/bin/bash
ripe_url="https://stat.ripe.net/data/country-resource-list/data.json?resource=RS"
folder="/home/che/scripts/archive-ripe-rs"
ipv4_rs_list="$folder/$(date -I)_rs_list"
file="$folder/$(date -I)_rs.rsc"
old_file="$(ls -1 $folder | grep $(date -d "$(date -I) last month" +%Y-%m)|grep .rsc)"
previous_file="$folder/$old_file"

if [ ! -d $folder ]; then
	mkdir -p $folder
fi

curl -s "$ripe_url" | python2 -c "import sys, json; print json.load(sys.stdin)['data']['resources']['ipv4']" | tr ' ' '\n' | sed 's/[^0-9./-]*//g' > $ipv4_rs_list

> $file

while read -r line || [[ -n "$line" ]]
do
	echo ":do { /ip firewall address-list add list=access-wan-geo-rs address=$line } on-error={}" >> $file
done < "$ipv4_rs_list"

router_ssh="ssh -T robot@192.168.11.254"
md5_current=$(md5sum "$file" | cut -d " " -f1)
md5_previous=$(md5sum "$previous_file" | cut -d " " -f1)

if [ $md5_current != $md5_previous ]; then
	> addlines
	> deladdress
	> dellines
	diff $previous_file $file | grep '> ' | sed 's/^> //' >> addlines
	diff $previous_file $file | grep '< '| sed 's/^.*address\=//' | sed 's/ .*//' >> deladdress
        if [[ -s addlines ]]; then
		$router_ssh < addlines
	fi
	if  [[ -s deladdress ]]; then
		while read -r adresa
		do
			echo ":do { /ip firewall address-list remove [find where list=access-wan-geo-rs address=$adresa] } on-error={}" >> dellines
		done < deladdress
		$router_ssh < dellines
	fi
	rm addlines deladdress dellines
else
	echo "The access-wan-geo-rs list has no changes compared to previous month."
fi
