#!/bin/bash

ripe_url="https://stat.ripe.net/data/announced-prefixes/data.json?resource=AS31042"
folder="/home/che/scripts/archive-ripe-bgp-sbb"
list_raw="$folder/$(date -I)_bgp-sbb_list"
list_rsc="$folder/$(date -I)_bgp-sbb.rsc"
list_rsc_old="$(ls -t1 $folder/*rsc | head -1)"

if [ ! -d $folder ]; then
  mkdir -p $folder
fi

curl -s $ripe_url | jq ".data.prefixes[].prefix" | sed -n '/:/!p' | sed 's/[^0-9./-]*//g' > $list_raw

> $list_rsc

while read -r line || [[ -n "$line" ]]
do
  echo ":do { /ip firewall address-list add list=bgp-sbb comment=AS31042 address=$line } on-error={}" >> $list_rsc
done < "$list_raw"

router_ssh="ssh -T robot@fw.lan"
md5_current=$(md5sum "$list_rsc" | cut -d " " -f1)
md5_previous=$(md5sum "$list_rsc_old" | cut -d " " -f1)

if [ "$md5_current" != "$md5_previous" ]; then
  > addlines
  > deladdress
  > dellines
  diff $list_rsc_old $list_rsc | grep '> ' | sed 's/^> //' >> addlines
  diff $list_rsc_old $list_rsc | grep '< '| sed 's/^.*address\=//' | sed 's/ .*//' >> deladdress
  if [[ -s deladdress ]]; then
    while read -r adresa
    do
      $router_ssh ":log info \"Changes detected in AS31042 compared to existing version. Removing entries from bgp-sbb address list.\""
      echo ":do { /ip firewall address-list remove [find where list=bgp-sbb comment=AS31042 address=$adresa] } on-error={}" >> dellines
    done < deladdress
    $router_ssh < dellines
  fi
  if [[ -s addlines ]]; then
    $router_ssh ":log info \"Changes detected in AS31042 compared to existing version. Adding entries to bgp-sbb address list.\""
    $router_ssh < addlines
  fi
  rm addlines deladdress dellines
else
  $router_ssh ":log info \"The bgp-sbb address list has no changes compared to the existing version.\""
fi