#!/bin/bash
ripe_bgp="https://stat.ripe.net/data/announced-prefixes/data.json?resource=AS31042"
ripe_mts="https://stat.ripe.net/data/announced-prefixes/data.json?resource=AS8400"
tmp_folder="/etc/iptables/tmp"
rules_folder="/etc/iptables/rules"
ipv4_bgp_sbb="$tmp_folder/$(date -I)_bgp_sbb.list"
ipv4_bgp_mts="$tmp_folder/$(date -I)_bgp_mts.list"
file="$rules_folder/$(date -I).fw.rules"

if [ ! -d $rules_folder ]; then
        mkdir -p $rules_folder
fi
if [ ! -d $tmp_folder ]; then
        mkdir -p $tmp_folder
fi

curl -s $ripe_bgp | jq ".data.prefixes[].prefix" | sed -n '/:/!p' | sed 's/[^0-9./-]*//g' > $ipv4_bgp_sbb
curl -s $ripe_mts | jq ".data.prefixes[].prefix" | sed -n '/:/!p' | sed 's/[^0-9./-]*//g' > $ipv4_bgp_mts

#CREATE IPTABLES RULES
> $file
cat <<EOF >> $file
# Generated by /root/scripts on $date
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
:BGP_SBB_MTS - [0:0]
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -i lo -j ACCEPT
-A INPUT -p udp -m udp --dport 58348 -m comment --comment "Wireguard" -j ACCEPT
-A INPUT -s 172.31.31.2,172.31.31.3,172.31.31.4 -m comment --comment "PC, Balboa, OPO through Wireguard" -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j BGP_SBB_MTS
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -m conntrack --ctstate INVALID -j DROP
-A FORWARD -i wg0 -j ACCEPT
-A FORWARD -i lo -j ACCEPT
EOF
while read -r line || [[ -n "$line" ]]
do
        echo "-A BGP_SBB_MTS -s $line -m comment --comment \"SBB\" -j ACCEPT" >> $file
done < "$ipv4_bgp_sbb"
while read -r line || [[ -n "$line" ]]
do
        echo "-A BGP_SBB_MTS -s $line -m comment --comment \"MTS\" -j ACCEPT" >> $file
done < "$ipv4_bgp_mts"
echo "COMMIT" >> $file

# Reload iptables with new rules
/sbin/iptables-restore < $file
